name: "Ensure Files Changed"
description: "Ensures files specified were changed in a PR, or can be used to ensure files were not changed"
author: "danieljimeneznz"

inputs:
  require-changes-to:
    description: "A list of files (or glob patterns) that represent the files that should be modified by a PR."
    required: false
  prevent-changes-to:
    description: "A list of files (or glob patterns) that represent the files that should not be modified by a PR."
    required: false
  token:
    description: "The GitHub token used to create an authenticated client."
    required: true

outputs:
  success:
    description: "The success of the validated files."

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "git-pull-request"
  color: "orange"
